groups:
- name: trackdb
  rules:
  - alert: trackdb_daily_refresh_has_not_run
    expr: (time() - trackdb_refresh_timestamp) / (60*60) > 24
    for: 1h
    labels:
      severity: severe
    annotations:
      summary: "TrackDB not updated in last 24 hours"
      description: "{{ $labels.instance }} {{ $labels.job }} refresh_timestamp_dt hasn't changed in over 24 hours"

- name: Core metrics
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: service_down
    expr: up == 0
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: host_cpu_rate
    expr: 100 - 100*avg(irate(node_cpu_seconds_total{mode='idle'}[10m])) > 80
    for: 10m
    labels:
      severity: severe
    annotations:
      summary: "CPU rate on {{ $labels.instance }} > 80%"
      description: "CPU rate on {{ $labels.instance }} > 80% for more than 10 minutes"

  - alert: host_free_disk_space
    expr: (node_filesystem_avail_bytes{fstype=~"ext.|xfs|zfs",instance!="jisc03:9100"}/node_filesystem_size_bytes{fstype=~"ext.|xfs|zfs",instance!="jisc03:9100"}) * 100 < 15
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Disk space free < 15% on {{ $labels.instance }}"
      description: "Disk space free on {{ $labels.instance }} has been less that 15% for more than 5 minutes"

  - alert: host_free_disk_space_jisc03
    expr: (node_filesystem_avail_bytes{fstype=~"ext.|xfs|zfs",instance="jisc03:9100"}/node_filesystem_size_bytes{fstype=~"ext.|xfs|zfs",instance="jisc03:9100"}) * 100 < 5
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Disk space free < 5% on {{ $labels.instance }}"
      description: "Disk space free on {{ $labels.instance }} has been less that 5% for more than 5 minutes"

  - alert: db_backup_failed
    expr: absent(ukwa_database_backup_size_bytes)
    for: 24h
    labels:
      severity: severe
    annotations:
      summary: "Databse back instance {{ $labels.instance }} failed to run"
      description: "{{ $labels.instance }} of job {{ $labels.job }} failed to run."

  - alert: predict_host_disk_space
    expr: min(predict_linear(node_filesystem_free{mountpoint=~"/|/data"}[48h], 2*7*24*3600)) by (instance, mountpoint) < 0
    for: 1h
    labels:
      severity: severe
    annotations:
      summary: "Disk space running out on {{ $labels.instance }} at {{ $labels.mountpoint }}"
      description: "Based on recent sampling, the disk is likely to will fill on volume {{ $labels.mountpoint }} within the next two weeks, for instance: {{ $labels.instance }}."

  - alert: daily_access_task_is_missing
    expr: absent(ukwa_task_event_timestamp{job=~"DailyAccessTasks"})
    for: 24h
    labels:
      severity: severe
    annotations:
      summary: "Task {{ $labels.job }} failed to run"
      description: "Job {{ $labels.job }} failed to run successfully."

  - alert: daily_ingest_task_is_missing
    expr: absent(ukwa_task_event_timestamp{job=~"DailyIngestTasks"})
    for: 24h
    labels:
      severity: severe
    annotations:
      summary: "Task {{ $labels.job }} failed to run"
      description: "Job {{ $labels.job }} failed to run successfully."

  - alert: daily_task_has_not_run
    expr: (time() - ukwa_task_event_timestamp{job=~"DailyAccessTasks|DailyIngestTasks", status="event.core.success"} ) / (60*60) > 24
    for: 2h
    labels:
      severity: severe
    annotations:
      summary: "Task {{ $labels.job }} failed to run"
      description: "Job {{ $labels.job }} failed to run successfully."

  - alert: nominet_task_has_not_run
    expr: (time() - ukwa_task_event_timestamp{job="NominetDomainListToHDFS", status="event.core.success"} ) / (60*60*24) > 31
    for: 2h
    labels:
      severity: severe
    annotations:
      summary: "Task {{ $labels.job }} failed to run"
      description: "Job {{ $labels.job }} failed to run successfully."

  - alert: crawl_launcher_has_not_run
    expr: (time() - ukwa_task_event_timestamp{job='crawl.LaunchCrawls', status="event.core.success"}) > 3600
    for: 10m
    labels:
      severity: severe
    annotations:
      summary: "Task {{ $labels.job }} failed to run"
      description: "Job {{ $labels.job }} failed to run successfully."
 
  - alert: fc_crawl_is_slow
    expr: sum(rate(kafka_log_logendoffset{topic="fc.crawled"}[10m])) < 5
    for: 30m
    labels:
      severity: severe
    annotations:
      summary: "The frequent crawl is not running as fast as expected!"
      description: "The frequent crawl does not appear to be running as fast as it should be."

  - alert: cpu_running_too_hot
    expr: max(node_hwmon_temp_celsius) by (instance) > 70
    for: 30m
    labels:
      severity: severe
    annotations:
      summary: "CPU running too hot?"
      description: "The CPU on {{ $labels.instance }} is running hot (>70C for 30mins)."
 
